### ISSUE TITLE
K closest points in O(n*log(K)), also Hello!

### ISSUE THREAD

**Issue by raspu** [hlxwell/leetcode-ruby#1]
https://github.com/hlxwell/leetcode-ruby/blob/590a4114b623e9c9864bd9acd6e8926be498b01a/k-closest-points.py#L8

This can be solved in O(n*log(K)) if you use a Heap. 

(Hi Michael! It's been a long time!)

**Comment by hlxwell** [comment]
@raspu Hey, buddy, long time no see, how are you doing? missed you a lot. you son is really cute :)

**Comment by hlxwell** [comment]
I think sorted() should use quicksort.

**Comment by raspu** [comment]
@hlxwell :). We are doing great, we also have been missing you guys a lot. Let's talk via other channel :p. 

About the problem, it's not about the sorting, you don't need to sort, you add all the element on a Heap with strict size of K (every time you insert an element that will make the Heap size K+1, you remove the largest leaf). After you finish, you have in the heap the K closest points.  As both inserting and removing elements from a Heap is O(log(K)) it will take you only O(n*log(K)) to find the K closest points. And as K is usually orders of magnitude smaller than n, it's basically O(n).

**Comment by hlxwell** [comment]
@raspu Bravo, You are a very smart boy. my genius friend. totally make sense.

Implement a heap has too many works. :) I am a lazy man.

**Comment by raspu** [comment]
@hlxwell You can use a priority queue also :). But it's not my original idea, I learnt this in a job interview... So I am not that smart :B.

**Comment by hlxwell** [comment]
Solved. @raspu 
Python has the priority queue integrated, very good.
https://github.com/hlxwell/leetcode-ruby/commit/fada309e939db3d0792bb8c068efa54a41ac13db
